/*
 * Ultrasonic.h
 *
 *  Created on: Oct 15, 2022
 *      Author: Eng AFS
 */

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include"std_types.h"
/*
 * Setup the direction for the trigger pin as output pin through the GPIO driver.
 * Setup the ICU call back function.
 * Initialize the ICU driver as required.
 */
void Ultrasonic_init(void);

/*
 * Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void);

/*
 * Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void);

/*
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void);


#endif /* ULTRASONIC_H_ */
